SELECT SQL_NO_CACHE COUNT(*) FROM sys_user;
EXPLAIN SELECT SQL_NO_CACHE COUNT(*) FROM sys_user WHERE USER_NAME >= '2';
#SELECT SQL_NO_CACHE COUNT(DISTINCT USER_NAME) FROM sys_user;
#SELECT SQL_NO_CACHE COUNT(*) FROM (SELECT SQL_NO_CACHE DISTINCT USER_NAME FROM sys_user) tmp;