EXPLAIN SELECT * FROM sys_user WHERE SUBSTR(USER_NAME FROM 1 FOR 3) = '100';
EXPLAIN SELECT * FROM sys_user WHERE USER_NAME LIKE '100%';
EXPLAIN SELECT * FROM sys_user WHERE ID*2=100;
EXPLAIN SELECT * FROM sys_user WHERE ID='50';